// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transactions.Model;

namespace Transactions.Migrations
{
    [DbContext(typeof(DBTransContext))]
    partial class DBTransContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transactions.Model.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<string>("FromUserId");

                    b.Property<string>("ToUserId");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new { Id = 1, Amount = 22.22, FromUserId = "123", ToUserId = "789" },
                        new { Id = 2, Amount = 23.22, FromUserId = "123", ToUserId = "789" },
                        new { Id = 3, Amount = 23.22, FromUserId = "789", ToUserId = "123" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
